/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    Breadcrumb: typeof import('./src/components/Layout/header/modules/breadcrumb.vue')['default']
    Buoy: typeof import('./src/components/widget/Buoy.vue')['default']
    Content: typeof import('./src/components/Layout/content/index.vue')['default']
    Footer: typeof import('./src/components/Layout/footer/index.vue')['default']
    FullScreem: typeof import('./src/components/Layout/header/modules/sysTools/utils/fullScreem.vue')['default']
    Header: typeof import('./src/components/Layout/header/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    MenuItem: typeof import('./src/components/Layout/sysMenu/menuItem/menuItem.vue')['default']
    Refresh: typeof import('./src/components/Layout/header/modules/sysTools/utils/refresh.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SysMenu: typeof import('./src/components/Layout/sysMenu/index.vue')['default']
    SysModal: typeof import('./src/components/SysModal/index.vue')['default']
    SysTable: typeof import('./src/components/sysTable/index.vue')['default']
    SysTools: typeof import('./src/components/Layout/header/modules/sysTools/index.vue')['default']
    Tabs: typeof import('./src/components/Layout/header/modules/tabs.vue')['default']
    UserTools: typeof import('./src/components/Layout/header/modules/userTools.vue')['default']
  }
}
