/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Buoy: typeof import('./src/components/widget/Buoy.vue')['default']
    Card: typeof import('./src/components/card/index.vue')['default']
    Content: typeof import('./src/components/Layout/content/index.vue')['default']
    Header: typeof import('./src/components/Layout/header/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SysMenu: typeof import('./src/components/Layout/sysMenu/index.vue')['default']
  }
}
