/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb'];
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem'];
    AButton: typeof import('ant-design-vue/es')['Button'];
    ACard: typeof import('ant-design-vue/es')['Card'];
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup'];
    ACol: typeof import('ant-design-vue/es')['Col'];
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider'];
    ADrawer: typeof import('ant-design-vue/es')['Drawer'];
    ADropdown: typeof import('ant-design-vue/es')['Dropdown'];
    AForm: typeof import('ant-design-vue/es')['Form'];
    AFormItem: typeof import('ant-design-vue/es')['FormItem'];
    AInput: typeof import('ant-design-vue/es')['Input'];
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber'];
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword'];
    ALayout: typeof import('ant-design-vue/es')['Layout'];
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider'];
    AMenu: typeof import('ant-design-vue/es')['Menu'];
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
    AModal: typeof import('ant-design-vue/es')['Modal'];
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm'];
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup'];
    ARow: typeof import('ant-design-vue/es')['Row'];
    ASelect: typeof import('ant-design-vue/es')['Select'];
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption'];
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu'];
    ASwitch: typeof import('ant-design-vue/es')['Switch'];
    ATable: typeof import('ant-design-vue/es')['Table'];
    ATabPane: typeof import('ant-design-vue/es')['TabPane'];
    ATabs: typeof import('ant-design-vue/es')['Tabs'];
    ATree: typeof import('ant-design-vue/es')['Tree'];
    ATreeSelect: typeof import('ant-design-vue/es')['TreeSelect'];
    AUpload: typeof import('ant-design-vue/es')['Upload'];
    Breadcrumb: typeof import('./src/components/Layout/header/modules/breadcrumb.vue')['default'];
    Buoy: typeof import('./src/components/widget/Buoy.vue')['default'];
    Content: typeof import('./src/components/Layout/content/index.vue')['default'];
    DictCheckbox: typeof import('./src/components/sysDict/modules/dictCheckbox.vue')['default'];
    DictRadio: typeof import('./src/components/sysDict/modules/dictRadio.vue')['default'];
    DictSelect: typeof import('./src/components/sysDict/modules/dictSelect.vue')['default'];
    DictText: typeof import('./src/components/sysDict/modules/dictText.vue')['default'];
    Footer: typeof import('./src/components/Layout/footer/index.vue')['default'];
    FullScreem: typeof import('./src/components/Layout/header/modules/sysTools/utils/fullScreem.vue')['default'];
    Header: typeof import('./src/components/Layout/header/index.vue')['default'];
    Layout: typeof import('./src/components/Layout/index.vue')['default'];
    Loading: typeof import('./src/components/Loading/index.vue')['default'];
    MenuItem: typeof import('./src/components/Layout/sysMenu/menuItem/menuItem.vue')['default'];
    Refresh: typeof import('./src/components/Layout/header/modules/sysTools/utils/refresh.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SysDict: typeof import('./src/components/sysDict/sysDict.vue')['default'];
    SysMenu: typeof import('./src/components/Layout/sysMenu/index.vue')['default'];
    SysModal: typeof import('./src/components/SysModal/index.vue')['default'];
    SysRemoveBtn: typeof import('./src/components/sysRemoveBtn/index.vue')['default'];
    SysSearch: typeof import('./src/components/sysSearch/index.vue')['default'];
    SysTable: typeof import('./src/components/sysTable/index.vue')['default'];
    SysTools: typeof import('./src/components/Layout/header/modules/sysTools/index.vue')['default'];
    SysUpload: typeof import('./src/components/sysUpload/index.vue')['default'];
    Tabs: typeof import('./src/components/Layout/header/modules/tabs.vue')['default'];
    UserTools: typeof import('./src/components/Layout/header/modules/userTools.vue')['default'];
  }
}
